# Generated by Django 3.0.3 on 2020-03-13 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=25, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_reg', models.DateField(auto_now_add=True)),
                ('rating', models.FloatField(default=0, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=255)),
                ('body_quest', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.UserProfile')),
                ('tag', models.ManyToManyField(to='catalog.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_answer', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(default=0, null=True)),
                ('flag', models.BooleanField(blank=True, default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.UserProfile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Question')),
            ],
        ),
    ]
