# Generated by Django 3.0.3 on 2020-03-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200330_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
