# Generated by Django 3.0.3 on 2020-03-04 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200304_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 4, 11, 46, 29, 52259, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
