# Generated by Django 3.0.3 on 2020-04-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200407_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='vote',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
