# Generated by Django 3.0.3 on 2020-03-29 12:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200329_1501'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='total_answer',
            field=models.IntegerField(default=0),
        ),
    ]
