# Generated by Django 3.0.3 on 2020-04-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200422_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
