# Generated by Django 3.0.3 on 2020-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200422_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
