# Generated by Django 3.0.3 on 2020-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200329_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='total_answer',
            new_name='total_answers',
        ),
    ]
