# Generated by Django 3.0.3 on 2020-04-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200422_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
