# Generated by Django 3.0.3 on 2020-04-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200423_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_liked',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_liked',
        ),
    ]
