# Generated by Django 3.0.3 on 2020-03-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200329_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerManager',
        ),
    ]
