# Generated by Django 3.0.3 on 2020-03-06 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200305_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 6, 9, 31, 47, 475588, tzinfo=utc), null=True),
        ),
    ]
